#!/bin/bash

video="${1:-}"
audio="${2:-}"

if [ "$video" == "" ]
then
    echo "Missing video file"
    echo "Usage: merge <video> <audio>"
    exit
fi

if [ "$audio" == "" ]
then
    echo "Missing audio file"
    echo "Usage: merge <video> <audio>"
    exit
fi

output="$(basename $video ".mp4")-merged"

echo "Merge $video && $audio > $output.mp4"

ffmpeg -nostats -loglevel 0 -i $audio -vn -acodec copy a.aac
ffmpeg -nostats -loglevel 0 -i $video -i a.aac -c:v copy -c:a aac -strict experimental $output.mp4

rm -rf a.aac
exit
