#!/bin/bash

random-string() {
    if [ "$2" == "true" ]
    then
        # https://gist.github.com/earthgecko/3089509#gistcomment-1346894
        cat /dev/urandom | tr -dc "a-zA-Z0-9!@#$%^&*()_+?><~\`;'" | fold -w ${1:-32} | head -n 1
    else
        # https://gist.github.com/earthgecko/3089509#gistcomment-1177367
        cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1
    fi
}

random-string
random-string 32 "true"
